version: '3.8'

services:
  web:
  build:
    context: ./app
    dockerfile: Dockerfile.prod
  command: gunicorn intradi.wsgi:application --bind 0.0.0.0:8000
  ports:
    - 8000:8000
  env_file:
    - ./.env.prod
  depends_on:
    - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=intradi
      - POSTGRES_PASSWORD=mi3987xl
      - POSTGRES_DB=intradi_dev

volumes:
  postgres_data: